In [1]:
# Setup

from dolo import *
from dolo import time_iteration
import dolark 
from dolark import HModel
from dolark.equilibrium import find_steady_state
from dolark.perturbation import perturb
from matplotlib import pyplot as plt
import numpy as np

In [2]:
#HModel reads the yaml file
aggmodel = HModel('Aiyagari.yaml')
aggmodel


In [3]:
aggmodel.features

{'ex-ante-identical': True,
 'conditional-processes': False,
 'iid-shocks': False}

In [4]:
#first check whether the one-agent sub-part of the mode works
from dolo import time_iteration
i_opts = {"N":2}
model = aggmodel.model
mc = model.exogenous.discretize(to='mc',options=[{},i_opts])
sol0 = time_iteration(model, details=True, dprocess=mc)

    calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.


------------------------------------------------
| N   |  Error     | Gain     | Time     | nit |
------------------------------------------------


    Did not converge


|   1 |  9.287e+01 |      nan |    1.799 |  10 |
|   2 |  3.087e+01 |    0.332 |    0.015 |   4 |
|   3 |  1.536e+01 |    0.498 |    0.016 |   4 |
|   4 |  9.155e+00 |    0.596 |    0.012 |   3 |
|   5 |  6.050e+00 |    0.661 |    0.012 |   3 |
|   6 |  4.273e+00 |    0.706 |    0.019 |   5 |
|   7 |  3.161e+00 |    0.740 |    0.016 |   3 |
|   8 |  2.418e+00 |    0.765 |    0.013 |   3 |
|   9 |  1.896e+00 |    0.784 |    0.012 |   3 |
|  10 |  1.514e+00 |    0.799 |    0.012 |   3 |
|  11 |  1.227e+00 |    0.810 |    0.009 |   2 |
|  12 |  1.004e+00 |    0.818 |    0.009 |   2 |
|  13 |  8.270e-01 |    0.824 |    0.009 |   2 |
|  14 |  6.845e-01 |    0.828 |    0.009 |   2 |
|  15 |  5.671e-01 |    0.828 |    0.009 |   2 |
|  16 |  4.696e-01 |    0.828 |    0.009 |   2 |
|  17 |  3.874e-01 |    0.825 |    0.009 |   2 |
|  18 |  3.156e-01 |    0.815 |    0.009 |   2 |
|  19 |  2.519e-01 |    0.798 |    0.046 |   2 |
|  20 |  1.960e-01 |    0.778 |    0.019 |   2 |
|  21 |  1.480e-01 |

In [5]:
eq = find_steady_state(aggmodel)
eq

Computing Initial Initial Rule... done
Computing Steady State...done


In [9]:
help(find_steady_state)

Help on function find_steady_state in module dolark.equilibrium:

find_steady_state(hmodel, dr0=None, verbose=True, distribs=None)



In [12]:
help(HModel)

Help on class HModel in module dolark.model:

class HModel(builtins.object)
 |  HModel(fname, i_options={}, dptype=None, debug=False)
 |  
 |  Methods defined here:
 |  
 |  A(self, grids, m0: 'n_e', μ0: 'n_m.N', xx0: 'n_m.N.n_x', y0: 'n_y', p: 'n_p')
 |  
 |  __get_calibration__(self)
 |  
 |  __init__(self, fname, i_options={}, dptype=None, debug=False)
 |      Initialize self.  See help(type(self)) for accurate signature.
 |  
 |  __set_changed__(self)
 |  
 |  check(self)
 |  
 |  get_starting_rule(self, method='improved_time_iteration', **kwargs)
 |  
 |  set_calibration(self, *pargs, **kwargs)
 |  
 |  τ(self, m, p)
 |  
 |  ----------------------------------------------------------------------
 |  Data descriptors defined here:
 |  
 |  E
 |  
 |  __dict__
 |      dictionary for instance variables (if defined)
 |  
 |  __weakref__
 |      list of weak references to the object (if defined)
 |  
 |  agent
 |  
 |  calibration
 |  
 |  distribution
 |  
 |  exogenous
 |  
 |  featu

In [13]:
help(eq)

Help on Equilibrium in module dolark.equilibrium object:

class Equilibrium(builtins.object)
 |  Equilibrium(aggmodel, m, μ, dr, y)
 |  
 |  Methods defined here:
 |  
 |  __init__(self, aggmodel, m, μ, dr, y)
 |      Initialize self.  See help(type(self)) for accurate signature.
 |  
 |  as_df(self)
 |  
 |  ----------------------------------------------------------------------
 |  Data descriptors defined here:
 |  
 |  __dict__
 |      dictionary for instance variables (if defined)
 |  
 |  __weakref__
 |      list of weak references to the object (if defined)



In [14]:
eq.dr

In [15]:
print(eq.dr)

In [29]:
eq.y  # y is the aggregate 

array([6.33612038])

In [31]:
eq.m # aggregate exogenous

array([0.])

In [36]:
eq.

array([[[-6.36785156e+00],
        [-1.00000008e-10],
        [ 6.36785156e+00],
        [ 1.30404988e+01],
        [ 1.97799265e+01],
        [ 2.65491263e+01],
        [ 3.33345063e+01],
        [ 4.01296972e+01],
        [ 4.69313047e+01],
        [ 5.37373349e+01],
        [ 6.05465350e+01],
        [ 6.73580799e+01],
        [ 7.41714038e+01],
        [ 8.09861066e+01],
        [ 8.78018980e+01],
        [ 9.46185622e+01],
        [ 1.01435936e+02],
        [ 1.08253894e+02],
        [ 1.15072339e+02],
        [ 1.21891192e+02],
        [ 1.28710391e+02],
        [ 1.35529887e+02],
        [ 1.42349637e+02],
        [ 1.49169609e+02],
        [ 1.55989774e+02],
        [ 1.62810107e+02],
        [ 1.69630591e+02],
        [ 1.76451204e+02],
        [ 1.83271943e+02],
        [ 1.90092768e+02],
        [ 1.96913729e+02],
        [ 2.03734689e+02]],

       [[-6.42715556e+00],
        [ 1.16335323e-01],
        [ 6.65982621e+00],
        [ 1.33674234e+01],
        [ 2.01237726e+01],

TypeError: 'DecisionRule' object is not iterable