In [145]:
# Setup

from dolo import *
from dolo.compiler.misc import CalibrationDict, calibration_to_vector
import dolark 
from dolark import HModel
from dolark.equilibrium import find_steady_state
from dolark.perturbation import perturb
from dolo import time_iteration, improved_time_iteration
from matplotlib import pyplot as plt
import numpy as np

In [146]:
#HModel reads the yaml file
aggmodel = HModel('Aiyagari-Copy1.yaml') # default calibration is sigma = 0.2, rho = 0.9, epsilon = 1
aggmodel

In [147]:
eq = find_steady_state(aggmodel)
eq

Computing Initial Initial Rule... done
Computing Steady State...done


In [148]:
df = eq.as_df()
a = df['a']
r = df['r']
w = df['w']
e = df['e']
μ = df['μ']
i = df['i']
    
#setup cnosumption and income
c = np.zeros((len(df),1))
income = np.zeros((len(df),1))
agg_c = 0
agg_inc = 0
# calculate consumption
for j in range(len(df)):
    c[j] = (1+r[j])*a[j] + w[j]*np.exp(e[j]) - i[j]
# calcuate income
for j in range(len(df)):
    income[j] = (r[j]+0.08)*a[j] + w[j]*math.exp(e[j])
# aggregate consumption and aggregat consumption
for j in range(len(df)):
    agg_c = agg_c + c[j]*μ[j]
    agg_inc = agg_inc + income[j]*μ[j]

saving_rate = 1 - agg_c/agg_inc

In [149]:
saving_rate

array([0.2437633])

In [150]:
savings = []
rho_values = np.linspace(0, 0.9, 4)   #change serial correlation coefficent "rho "in {0, 0.3, 0.6, 0.9}
sig_values = np.linspace(0.2, 0.4, 2) #change the variance of labor shocks "sig" in {0.2, 0.4}
epsilon_values = np.linspace(1, 5, 3)       #change the coefficient of risk aversion {1,3,5}

for l in epsilon_values:
    aggmodel.model.set_calibration( epsilon = l)
    for n in sig_values:
        aggmodel.model.set_calibration( sig = n )
        for m in rho_values:
            aggmodel.model.set_calibration( rho=m )
            eq = find_steady_state(aggmodel)
            df = eq.as_df()
            a = df['a']
            r = df['r']
            w = df['w']
            e = df['e']
            μ = df['μ']
            i = df['i']
    
            #setup cnosumption and income
            c = np.zeros((len(df),1))
            income = np.zeros((len(df),1))
            agg_c = 0
            agg_inc = 0
        
            # calculate consumption
            for j in range(len(df)):
                c[j] = (1+r[j])*a[j] + w[j]*math.exp(e[j]) - i[j]
            # calcuate income
            for j in range(len(df)):
                income[j] = (r[j]+0.08)*a[j] + w[j]*np.exp(e[j])   #0.08 is the depreciation rate
            
            # aggregate consumption and aggregat consumption
            for j in range(len(df)):
                agg_c = agg_c + c[j]*μ[j]
                agg_inc = agg_inc + income[j]*μ[j]
            
            saving_rate= 1 - agg_c/agg_inc
            
            #record the calibrated saving rate every time
            savings.append(saving_rate)
    

Computing Initial Initial Rule... done
Computing Steady State...done
Computing Initial Initial Rule... done
Computing Steady State...done
Computing Initial Initial Rule... done
Computing Steady State...done
Computing Initial Initial Rule... done
Computing Steady State...done
Computing Initial Initial Rule... done
Computing Steady State...done
Computing Initial Initial Rule... done
Computing Steady State...done
Computing Initial Initial Rule... done
Computing Steady State...done
Computing Initial Initial Rule... done
Computing Steady State...done
Computing Initial Initial Rule... done
Computing Steady State...done
Computing Initial Initial Rule... done
Computing Steady State...done
Computing Initial Initial Rule... done
Computing Steady State...done
Computing Initial Initial Rule... done
Computing Steady State...done
Computing Initial Initial Rule... done
Computing Steady State...done
Computing Initial Initial Rule... done
Computing Steady State...done
Computing Initial Initial Rule... 

In [151]:
savings

[array([0.24275118]),
 array([0.24280436]),
 array([0.24325385]),
 array([0.2437633]),
 array([0.24397777]),
 array([0.24475714]),
 array([0.2465101]),
 array([0.24745332]),
 array([0.25657752]),
 array([0.25732593]),
 array([0.26078807]),
 array([0.2837639]),
 array([0.26799146]),
 array([0.27172016]),
 array([0.28351045]),
 array([0.36529834]),
 array([0.26694438]),
 array([0.26829488]),
 array([0.27408014]),
 array([0.31640614]),
 array([0.28352314]),
 array([0.28936891]),
 array([0.30801935]),
 array([0.44488939])]